import { Inter } from 'next/font/google'
import './estilos-miztli.css'

import * as React from 'react';
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';

import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] })



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({children}) {


  return (
    <React.Fragment>
      <CssBaseline />
      <AppBar className='barra-menu'>
        <Toolbar>
          <Image
            src="/img/logo.svg"
            width={48}
            height={48}
            alt="Picture of the author"
          />
        </Toolbar>
      </AppBar>
      <Toolbar id="back-to-top-anchor" />
      <Container>
        <Box sx={{ my: 2 }}>
          {children}
        </Box>
      </Container>

    </React.Fragment>
  );
}
